version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: academy_final_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - academy_data:/var/lib/postgresql/data

  web:
    image: bunyakorngoko/academyfinal
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

volumes:
  academy_data:
